version: "3"

services:
  db_dev:
    image: postgres
    environment:
      POSTGRES_USER: homemPeludoChorando
      POSTGRES_PASSWORD: "n@oTem0sVagAs"
      POSTGRES_DB: movie_club_dev
    ports:
      - "5445:5432"
  db_test:
    image: postgres
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: "testing"
      POSTGRES_DB: movie_club_test
    ports:
      - "5446:5432"
